In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the csv file  --> Data/Noida_authority_plots_Simple_linear_regression.csv
df = pd.read_csv("Data/Noida_authority_plots_Simple_linear_regression.csv")
df

Amount_in_Crore  Land_in_Bigha
0                 1            0.1
1                 2            0.2
2                 3            0.3
3                 4            0.4
4                 5            0.5
5                 6            0.6
6                 7            0.7
7                 8            0.8
8                 9            0.9
9                10            1.0
10               11            1.1
11               12            1.2
12               13            1.3
13               14            1.4
14               15            1.5
15               16            1.6
16               17            1.7
17               18            1.8
18               19            1.9
19               20            2.0
20               21            2.1
21               22            2.2
22               23            2.3
23               24            2.4
24               25            2.5
25               26            2.6
26               27            2.7
27               28            2.8
28               29            2.9
29               30            3.0
30               31            3.1
31               32            3.2
32               33            3.3
33               34            3.4
34               35            3.5
35               36            3.6
36               37            3.7
37               38            3.8
38               39            3.9
39               40            4.0
40               41            4.1
41               42            4.2
42               43            4.3
43               44            4.4
44               45            4.5
45               46            4.6
46               47            4.7
47               48            4.8
48               49            4.9
49               50            5.0

In [4]:
df.columns  # Find the all columns for get all columns name from the pd DataFrame

Index(['Amount_in_Crore', 'Land_in_Bigha'], dtype='object')

In [7]:
X = df[["Amount_in_Crore"]]   # --> 2D is required
y = df["Land_in_Bigha"]
X

Amount_in_Crore
0                 1
1                 2
2                 3
3                 4
4                 5
5                 6
6                 7
7                 8
8                 9
9                10
10               11
11               12
12               13
13               14
14               15
15               16
16               17
17               18
18               19
19               20
20               21
21               22
22               23
23               24
24               25
25               26
26               27
27               28
28               29
29               30
30               31
31               32
32               33
33               34
34               35
35               36
36               37
37               38
38               39
39               40
40               41
41               42
42               43
43               44
44               45
45               46
46               47
47               48
48               49
49               50

In [9]:
# Now i am going to start train_test_split
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test  =  train_test_split(X, y, test_size = 0.2, random_state = 42)
X_test

Amount_in_Crore
13               14
39               40
30               31
45               46
17               18
48               49
26               27
25               26
32               33
19               20

In [11]:
# Now i am going to train the model using LinearRegression
from sklearn.linear_model import LinearRegression

# Create an object
model = LinearRegression()
# Now train the model
model.fit(X_train, y_train)

LinearRegression()

In [13]:
# Now i am going to test the model 
model.predict([[50]])

E:\ML_Class_8_30_am\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.])

In [14]:
model.predict([[100]])

E:\ML_Class_8_30_am\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.])

In [15]:
model.predict([[1000]])

E:\ML_Class_8_30_am\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([100.])

In [16]:
model.predict([[10000]])

E:\ML_Class_8_30_am\ml_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1000.])

In [20]:
X_test

Amount_in_Crore
13               14
39               40
30               31
45               46
17               18
48               49
26               27
25               26
32               33
19               20

In [19]:
# Now Create a y_pred variable using X_test

y_pred = model.predict(X_test)
y_pred


array([1.4, 4. , 3.1, 4.6, 1.8, 4.9, 2.7, 2.6, 3.3, 2. ])

In [21]:
# Now i am going to check the accuracy of the model using r2
# =============================================================
# r2 == 1  --> Perfect fit
# r2 > 0.9 --> Excellent
# r2 < 0.5 --> Bad Model
# =============================================================
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

1.0